### ISSUE TITLE
Test display warnings and unhandled promises

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/wendigo#135]
```
    ✓ KeyPress
    ✓ KeyPress Multiple Keys
Assertion failed: Unknown key: "NotAKey"
    ✓ KeyPress Invalud Input
(node:13195) UnhandledPromiseRejectionWarning: Error: Expected different error thrown
 [Expect] Error: Unknown key: "NotAKey" 
 [Actual] Error: Cannot read property 'key' of undefined
    at Object.assert.throws (/home/angrykoala/Git/wendigo/tests/test_utils.js:25:27)
    at expectedException (assert.js:489:19)
    at expectsError (assert.js:577:16)
    at Function.throws (assert.js:608:3)
    at Object.assertThrowsAsync (/home/angrykoala/Git/wendigo/tests/test_utils.js:21:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 267)
(node:13195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
_type tests_

```
  Open
    ✓ Open Fails
    ✓ Before Open Fails
    ✓ Assert Before Open Fails
    ✓ Assert Before Open Fails
    ✓ Open And Close (38ms)
Assertion failed: Protocol error: Connection closed. Most likely the page has been closed.
```
_Open test_

This must be fixed before release

**Comment by angrykoala** [comment]
Happening on 0.7.4 and 0.7.3

**Comment by angrykoala** [comment]
Some of these assertion failed messages are due to how node@10 handles console.assertion
