### ISSUE TITLE
Gitlab CI tests fail

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/wendigo#399]
Auth module tests are failing in GitlabCI since dependencies where updated. Release blocked until fixed

**Comment by angrykoala** [comment]
Bump to older dependencies not working, stacktrace:
```

  Auth
    1) No Auth


  728 passing (1m)
  4 pending
  1 failing

  1) Auth
       No Auth:
     AssertionError [ERR_ASSERTION]: [assert.text] Expected element ".auth-res" to have text "{"httpAuth":null,"authHeader":null}", "
    " found.
      at new AssertionError (internal/assert.js:269:11)
      at new AssertionError (dist/lib/errors.js:11:9)
      at obj.<anonymous> (dist/lib/browser/assertions/assertions_core.js:110:27)
      at Generator.next (<anonymous>)
      at fulfilled (dist/lib/browser/assertions/assertions_core.js:13:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)



npm ERR! Test failed.  See above for more details.
```

**Comment by angrykoala** [comment]
First commit causing Gitlab CI to fail: https://gitlab.com/angrykoala/wendigo/commit/1c62841c05e170a75ffe7aac8234e7f540d9a6db
